package crosslanguage

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pauvalls/arx/internal/domain"
	"github.com/pauvalls/arx/internal/ports"
)

// CrossLanguageDetector detects dependencies between files across languages
// by matching source definitions (e.g., .proto files) to generated files (e.g., .pb.go).
type CrossLanguageDetector struct {
	cfg *domain.CrossLanguageConfig
}

// New creates a new CrossLanguageDetector with the given config mappings.
func New(cfg *domain.CrossLanguageConfig) *CrossLanguageDetector {
	return &CrossLanguageDetector{cfg: cfg}
}

// Name returns the detector name.
func (d *CrossLanguageDetector) Name() string {
	return "cross-language"
}

// Detect checks if this detector has any configured mappings.
func (d *CrossLanguageDetector) Detect(_ context.Context, _ string) (bool, error) {
	if d.cfg == nil {
		return false, nil
	}
	return len(d.cfg.Mappings) > 0, nil
}

// ExtractImports finds cross-language dependencies by matching source files
// (e.g., .proto) to generated files (e.g., .pb.go) using config-defined
// glob patterns and generated-file header verification.
func (d *CrossLanguageDetector) ExtractImports(_ context.Context, projectRoot string, _ []domain.Layer) ([]domain.Dependency, error) {
	if d.cfg == nil || len(d.cfg.Mappings) == 0 {
		return nil, nil
	}

	// Verify project root exists and is a directory
	info, err := os.Stat(projectRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("accessing project root: %w", err)
	}
	if !info.IsDir() {
		return nil, nil
	}

	var dependencies []domain.Dependency

	for _, mapping := range d.cfg.Mappings {
		mapping := mapping // capture
		deps, err := d.processMapping(mapping, projectRoot)
		if err != nil {
			// Log and continue — don't fail the whole check on one mapping
			continue
		}
		dependencies = append(dependencies, deps...)
	}

	return dependencies, nil
}

// processMapping handles a single CrossLanguageMapping, matching source files
// to generated files by stem and verifying generated headers.
func (d *CrossLanguageDetector) processMapping(mapping domain.CrossLanguageMapping, projectRoot string) ([]domain.Dependency, error) {
	// Glob for source files
	sourcePattern := filepath.Join(projectRoot, mapping.SourcePattern)
	sourceFiles, err := filepath.Glob(sourcePattern)
	if err != nil {
		// Invalid pattern — skip this mapping
		return nil, nil
	}

	// Glob for generated files
	generatedPattern := filepath.Join(projectRoot, mapping.GeneratedPattern)
	generatedFiles, err := filepath.Glob(generatedPattern)
	if err != nil {
		return nil, nil
	}

	if len(sourceFiles) == 0 || len(generatedFiles) == 0 {
		return nil, nil
	}

	// Build stem → filepath map for generated files
	generatedStems := make(map[string]string, len(generatedFiles))
	for _, gf := range generatedFiles {
		stem := stemFromPath(gf)
		if _, exists := generatedStems[stem]; !exists {
			generatedStems[stem] = gf
		}
	}

	var dependencies []domain.Dependency

	for _, sf := range sourceFiles {
		stem := stemFromPath(sf)
		gf, ok := generatedStems[stem]
		if !ok {
			continue
		}

		// Verify the generated file has a protoc-gen or @generated header
		if !hasGeneratedHeader(gf) {
			continue
		}

		relSrc, _ := filepath.Rel(projectRoot, sf)
		relGen, _ := filepath.Rel(projectRoot, gf)
		if relSrc == "" {
			relSrc = sf
		}
		if relGen == "" {
			relGen = gf
		}

		dependencies = append(dependencies, domain.Dependency{
			SourceFile: relSrc,
			SourceLine: 1,
			ImportPath: relGen,
			Language:   "cross",
		})
	}

	return dependencies, nil
}

// stemFromPath extracts the base filename without any extensions.
// e.g., "/path/to/order.proto" → "order", "order.pb.go" → "order"
func stemFromPath(p string) string {
	base := filepath.Base(p)
	if idx := strings.Index(base, "."); idx >= 0 {
		return base[:idx]
	}
	return base
}

// hasGeneratedHeader checks if the first line of the file contains
// a protoc-gen or @generated header comment.
func hasGeneratedHeader(filePath string) bool {
	f, err := os.Open(filePath)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	if !scanner.Scan() {
		return false
	}

	firstLine := scanner.Text()
	return strings.Contains(firstLine, "// Code generated by protoc-gen-") ||
		strings.Contains(firstLine, "// @generated")
}

// Ensure CrossLanguageDetector implements ports.Detector interface.
var _ ports.Detector = (*CrossLanguageDetector)(nil)
