package crosslanguage

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/pauvalls/arx/internal/domain"
)

func TestName(t *testing.T) {
	d := New(&domain.CrossLanguageConfig{})
	if got := d.Name(); got != "cross-language" {
		t.Errorf("Name() = %q, want %q", got, "cross-language")
	}
}

func TestDetect(t *testing.T) {
	t.Run("with mappings returns true", func(t *testing.T) {
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		ok, err := d.Detect(context.Background(), "/tmp")
		if err != nil {
			t.Fatalf("Detect() error = %v", err)
		}
		if !ok {
			t.Errorf("Detect() = false, want true")
		}
	})

	t.Run("empty mappings returns false", func(t *testing.T) {
		d := New(&domain.CrossLanguageConfig{})
		ok, err := d.Detect(context.Background(), "/tmp")
		if err != nil {
			t.Fatalf("Detect() error = %v", err)
		}
		if ok {
			t.Errorf("Detect() = true, want false")
		}
	})

	t.Run("nil config returns false", func(t *testing.T) {
		d := New(nil)
		ok, err := d.Detect(context.Background(), "/tmp")
		if err != nil {
			t.Fatalf("Detect() error = %v", err)
		}
		if ok {
			t.Errorf("Detect() = true, want false")
		}
	})
}

func TestExtractImports(t *testing.T) {
	t.Run("empty mappings returns empty", func(t *testing.T) {
		d := New(&domain.CrossLanguageConfig{})
		deps, err := d.ExtractImports(context.Background(), t.TempDir(), nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0", len(deps))
		}
	})

	t.Run("nil config returns empty", func(t *testing.T) {
		d := New(nil)
		deps, err := d.ExtractImports(context.Background(), t.TempDir(), nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0", len(deps))
		}
	})

	t.Run("no matching source files returns empty", func(t *testing.T) {
		tmpDir := t.TempDir()
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0", len(deps))
		}
	})

	t.Run("no matching generated files returns empty", func(t *testing.T) {
		tmpDir := t.TempDir()
		if err := os.WriteFile(filepath.Join(tmpDir, "order.proto"), []byte("syntax = \"proto3\";\n"), 0644); err != nil {
			t.Fatal(err)
		}
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0", len(deps))
		}
	})

	t.Run("stem mismatch returns empty", func(t *testing.T) {
		tmpDir := t.TempDir()
		if err := os.WriteFile(filepath.Join(tmpDir, "order.proto"), []byte("syntax = \"proto3\";\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "user.pb.go"), []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n"), 0644); err != nil {
			t.Fatal(err)
		}
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0", len(deps))
		}
	})

	t.Run("generated with valid protoc-gen header emits dependency", func(t *testing.T) {
		tmpDir := t.TempDir()
		if err := os.WriteFile(filepath.Join(tmpDir, "order.proto"), []byte("syntax = \"proto3\";\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "order.pb.go"), []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage order\n"), 0644); err != nil {
			t.Fatal(err)
		}
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 1 {
			t.Fatalf("ExtractImports() returned %d deps, want 1", len(deps))
		}
		if deps[0].SourceFile != "order.proto" {
			t.Errorf("SourceFile = %q, want %q", deps[0].SourceFile, "order.proto")
		}
		if deps[0].ImportPath != "order.pb.go" {
			t.Errorf("ImportPath = %q, want %q", deps[0].ImportPath, "order.pb.go")
		}
		if deps[0].Language != "cross" {
			t.Errorf("Language = %q, want %q", deps[0].Language, "cross")
		}
		if deps[0].SourceLine != 1 {
			t.Errorf("SourceLine = %d, want 1", deps[0].SourceLine)
		}
	})

	t.Run("generated with @generated header emits dependency", func(t *testing.T) {
		tmpDir := t.TempDir()
		if err := os.WriteFile(filepath.Join(tmpDir, "user.proto"), []byte("syntax = \"proto3\";\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "user.pb.go"), []byte("// @generated\npackage user\n"), 0644); err != nil {
			t.Fatal(err)
		}
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 1 {
			t.Fatalf("ExtractImports() returned %d deps, want 1", len(deps))
		}
	})

	t.Run("non-generated file is rejected by header verification", func(t *testing.T) {
		tmpDir := t.TempDir()
		if err := os.WriteFile(filepath.Join(tmpDir, "order.proto"), []byte("syntax = \"proto3\";\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "order.go"), []byte("package order\n"), 0644); err != nil {
			t.Fatal(err)
		}
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0", len(deps))
		}
	})

	t.Run("unreadable generated file is skipped gracefully", func(t *testing.T) {
		tmpDir := t.TempDir()
		if err := os.WriteFile(filepath.Join(tmpDir, "order.proto"), []byte("syntax = \"proto3\";\n"), 0644); err != nil {
			t.Fatal(err)
		}
		// Create a file that matches the stem but can't be read — just the name, no content, then make it unreadable
		genPath := filepath.Join(tmpDir, "order.pb.go")
		if err := os.WriteFile(genPath, []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if err := os.Chmod(genPath, 0000); err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { os.Chmod(genPath, 0644) })

		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0 (unreadable file should be skipped)", len(deps))
		}
	})

	t.Run("nonexistent project root returns empty", func(t *testing.T) {
		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), "/nonexistent/path", nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 0 {
			t.Errorf("ExtractImports() returned %d deps, want 0", len(deps))
		}
	})

	t.Run("multiple mappings work together", func(t *testing.T) {
		tmpDir := t.TempDir()
		// First mapping: proto → pb.go
		if err := os.WriteFile(filepath.Join(tmpDir, "order.proto"), []byte("syntax = \"proto3\";\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "order.pb.go"), []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n"), 0644); err != nil {
			t.Fatal(err)
		}
		// Second mapping: graphql → generated.go (with protoc-gen-grpc-gateway header)
		if err := os.WriteFile(filepath.Join(tmpDir, "schema.graphql"), []byte("type Query {\n  hello: String\n}\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, "schema.generated.go"), []byte("// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.\n"), 0644); err != nil {
			t.Fatal(err)
		}
		// Also a non-matching file for graphql (stem mismatch)
		if err := os.WriteFile(filepath.Join(tmpDir, "other.graphql"), []byte("type Mutation {\n  create: Boolean\n}\n"), 0644); err != nil {
			t.Fatal(err)
		}

		d := New(&domain.CrossLanguageConfig{
			Mappings: []domain.CrossLanguageMapping{
				{SourcePattern: "*.proto", GeneratedPattern: "*.pb.go", GeneratedLanguage: "go"},
				{SourcePattern: "*.graphql", GeneratedPattern: "*.generated.go", GeneratedLanguage: "go"},
			},
		})
		deps, err := d.ExtractImports(context.Background(), tmpDir, nil)
		if err != nil {
			t.Fatalf("ExtractImports() error = %v", err)
		}
		if len(deps) != 2 {
			t.Fatalf("ExtractImports() returned %d deps, want 2", len(deps))
		}
	})
}

func TestStemFromPath(t *testing.T) {
	tests := []struct {
		path string
		want string
	}{
		{"/path/to/order.proto", "order"},
		{"order.pb.go", "order"},
		{"order", "order"},
		{"/absolute/path/to/user.pb.go", "user"},
		{"my.service.proto", "my"},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			if got := stemFromPath(tt.path); got != tt.want {
				t.Errorf("stemFromPath(%q) = %q, want %q", tt.path, got, tt.want)
			}
		})
	}
}

func TestHasGeneratedHeader(t *testing.T) {
	t.Run("protoc-gen header returns true", func(t *testing.T) {
		tmpDir := t.TempDir()
		fp := filepath.Join(tmpDir, "test.go")
		if err := os.WriteFile(fp, []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage test\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if !hasGeneratedHeader(fp) {
			t.Errorf("hasGeneratedHeader() = false, want true")
		}
	})

	t.Run("@generated header returns true", func(t *testing.T) {
		tmpDir := t.TempDir()
		fp := filepath.Join(tmpDir, "test.go")
		if err := os.WriteFile(fp, []byte("// @generated\npackage test\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if !hasGeneratedHeader(fp) {
			t.Errorf("hasGeneratedHeader() = false, want true")
		}
	})

	t.Run("plain go file returns false", func(t *testing.T) {
		tmpDir := t.TempDir()
		fp := filepath.Join(tmpDir, "test.go")
		if err := os.WriteFile(fp, []byte("package test\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if hasGeneratedHeader(fp) {
			t.Errorf("hasGeneratedHeader() = true, want false")
		}
	})

	t.Run("nonexistent file returns false", func(t *testing.T) {
		if hasGeneratedHeader("/nonexistent/file.go") {
			t.Errorf("hasGeneratedHeader() = true, want false")
		}
	})

	t.Run("grpc-gateway header returns true", func(t *testing.T) {
		tmpDir := t.TempDir()
		fp := filepath.Join(tmpDir, "test.pb.gw.go")
		if err := os.WriteFile(fp, []byte("// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.\n"), 0644); err != nil {
			t.Fatal(err)
		}
		if !hasGeneratedHeader(fp) {
			t.Errorf("hasGeneratedHeader() = false, want true")
		}
	})
}
