package crosslanguage

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pauvalls/arx/internal/domain"
	"github.com/pauvalls/arx/internal/ports"
)

// CrossLanguageDetector detects dependencies between files across languages
// by matching source definitions (e.g., .proto files) to generated files (e.g., .pb.go).
type CrossLanguageDetector struct {
	cfg *domain.CrossLanguageConfig
}

// New creates a new CrossLanguageDetector with the given config mappings.
func New(cfg *domain.CrossLanguageConfig) *CrossLanguageDetector {
	return &CrossLanguageDetector{cfg: cfg}
}

// Name returns the detector name.
func (d *CrossLanguageDetector) Name() string {
	return "cross-language"
}

// Detect checks if this detector has any configured mappings.
func (d *CrossLanguageDetector) Detect(_ context.Context, _ string) (bool, error) {
	if d.cfg == nil {
		return false, nil
	}
	return len(d.cfg.Mappings) > 0, nil
}

// ExtractImports finds cross-language dependencies by matching source files
// (e.g., .proto) to generated files (e.g., .pb.go) using config-defined
// glob patterns and generated-file header verification.
func (d *CrossLanguageDetector) ExtractImports(_ context.Context, projectRoot string, _ []domain.Layer) ([]domain.Dependency, error) {
	if d.cfg == nil || len(d.cfg.Mappings) == 0 {
		return nil, nil
	}

	// Verify project root exists and is a directory
	info, err := os.Stat(projectRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("accessing project root: %w", err)
	}
	if !info.IsDir() {
		return nil, nil
	}

	var dependencies []domain.Dependency

	for _, mapping := range d.cfg.Mappings {
		mapping := mapping // capture
		deps, err := d.processMapping(mapping, projectRoot)
		if err != nil {
			// Log and continue — don't fail the whole check on one mapping
			continue
		}
		dependencies = append(dependencies, deps...)
	}

	return dependencies, nil
}

// processMapping handles a single CrossLanguageMapping, matching source files
// to generated files by stem (or glob) and verifying generated headers.
func (d *CrossLanguageDetector) processMapping(mapping domain.CrossLanguageMapping, projectRoot string) ([]domain.Dependency, error) {
	// Glob for source files
	sourcePattern := filepath.Join(projectRoot, mapping.SourcePattern)
	sourceFiles, err := filepath.Glob(sourcePattern)
	if err != nil {
		return nil, nil
	}

	// Glob for generated files
	generatedPattern := filepath.Join(projectRoot, mapping.GeneratedPattern)
	generatedFiles, err := filepath.Glob(generatedPattern)
	if err != nil {
		return nil, nil
	}

	if len(sourceFiles) == 0 || len(generatedFiles) == 0 {
		return nil, nil
	}

	// Determine match strategy (default: stem)
	strategy := mapping.MatchStrategy
	if strategy == "" {
		strategy = "stem"
	}

	var dependencies []domain.Dependency

	switch strategy {
	case "glob":
		// Glob strategy: every source file deps on every generated file
		// Used for OpenAPI specs, shared configs, etc.
		for _, sf := range sourceFiles {
			for _, gf := range generatedFiles {
				// Verify header if custom patterns provided or use defaults
				if !d.matchesHeader(gf, mapping.HeaderPatterns) {
					continue
				}
				deps := makeDep(sf, gf, projectRoot)
				if deps != nil {
					dependencies = append(dependencies, *deps)
				}
			}
		}

	default: // "stem" strategy (default, backward compatible)
		// Build stem → filepath map for generated files
		generatedStems := make(map[string]string, len(generatedFiles))
		for _, gf := range generatedFiles {
			stem := stemFromPath(gf)
			if _, exists := generatedStems[stem]; !exists {
				generatedStems[stem] = gf
			}
		}

		for _, sf := range sourceFiles {
			stem := stemFromPath(sf)
			gf, ok := generatedStems[stem]
			if !ok {
				continue
			}

			if !d.matchesHeader(gf, mapping.HeaderPatterns) {
				continue
			}

			deps := makeDep(sf, gf, projectRoot)
			if deps != nil {
				dependencies = append(dependencies, *deps)
			}
		}
	}

	return dependencies, nil
}

// makeDep creates a Dependency between two files, using relative paths.
func makeDep(src, gen, projectRoot string) *domain.Dependency {
	relSrc, _ := filepath.Rel(projectRoot, src)
	relGen, _ := filepath.Rel(projectRoot, gen)
	if relSrc == "" {
		relSrc = src
	}
	if relGen == "" {
		relGen = gen
	}
	return &domain.Dependency{
		SourceFile: relSrc,
		SourceLine: 1,
		ImportPath: relGen,
		Language:   "cross",
	}
}

// stemFromPath extracts the base filename without any extensions.
// e.g., "/path/to/order.proto" → "order", "order.pb.go" → "order"
func stemFromPath(p string) string {
	base := filepath.Base(p)
	if idx := strings.Index(base, "."); idx >= 0 {
		return base[:idx]
	}
	return base
}

// defaultHeaderPatterns are the default header patterns checked when
// no custom header_patterns are specified in the mapping.
var defaultHeaderPatterns = []string{
	"// Code generated by protoc-gen-",
	"// @generated",
	"// Generated by OpenAPI Generator",
	"// auto-generated",
	"// Code generated by protoc-gen-grpc-gateway",
}

// matchesHeader checks if a file's first line matches any of the given
// header patterns. If customPatterns is empty, uses default patterns.
func (d *CrossLanguageDetector) matchesHeader(filePath string, customPatterns []string) bool {
	patterns := customPatterns
	if len(patterns) == 0 {
		patterns = defaultHeaderPatterns
	}

	f, err := os.Open(filePath)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	if !scanner.Scan() {
		return false
	}

	firstLine := scanner.Text()
	for _, p := range patterns {
		if strings.Contains(firstLine, p) {
			return true
		}
	}
	return false
}

// Ensure CrossLanguageDetector implements ports.Detector interface.
var _ ports.Detector = (*CrossLanguageDetector)(nil)
