package output

import (
	"fmt"
	"strings"
	"time"

	"github.com/pauvalls/arx/internal/domain"
	"github.com/pauvalls/arx/internal/ports"
)

// MarkdownReporter implements ports.Reporter for Markdown output
type MarkdownReporter struct {
	version string
}

// NewMarkdownReporter creates a new Markdown reporter
func NewMarkdownReporter() *MarkdownReporter {
	return &MarkdownReporter{
		version: "0.2.0",
	}
}

// Report implements ports.Reporter interface
func (r *MarkdownReporter) Report(violations []domain.Violation, format ports.OutputFormat) error {
	report := r.buildMarkdownReport(violations)
	fmt.Println(report)
	return nil
}

// buildMarkdownReport constructs the Markdown report
func (r *MarkdownReporter) buildMarkdownReport(violations []domain.Violation) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Architecture Audit Report\n\n")
	sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("**Tool:** Arx v%s\n\n", r.version))

	// Executive Summary
	sb.WriteString("## Executive Summary\n\n")

	totalErrors := 0
	totalWarnings := 0
	totalInfo := 0
	violationsByFile := make(map[string]int)
	violationsByRule := make(map[string]int)

	for _, v := range violations {
		violationsByFile[v.File]++
		violationsByRule[v.RuleID]++

		switch strings.ToLower(string(v.Severity)) {
		case "error":
			totalErrors++
		case "warning":
			totalWarnings++
		case "info":
			totalInfo++
		}
	}

	sb.WriteString(fmt.Sprintf("| Metric | Count |\n"))
	sb.WriteString(fmt.Sprintf("|--------|-------|\n"))
	sb.WriteString(fmt.Sprintf("| Total Violations | %d |\n", len(violations)))
	sb.WriteString(fmt.Sprintf("| Errors | %d |\n", totalErrors))
	sb.WriteString(fmt.Sprintf("| Warnings | %d |\n", totalWarnings))
	sb.WriteString(fmt.Sprintf("| Info | %d |\n", totalInfo))
	sb.WriteString(fmt.Sprintf("| Files Affected | %d |\n", len(violationsByFile)))
	sb.WriteString(fmt.Sprintf("| Rules Violated | %d |\n\n", len(violationsByRule)))

	if len(violations) == 0 {
		sb.WriteString("✅ **No violations found!** Your architecture is clean.\n\n")
		return sb.String()
	}

	// Violations by Layer
	sb.WriteString("## Violations by Layer\n\n")
	sb.WriteString("| Source Layer | Target Layer | Count |\n")
	sb.WriteString("|--------------|--------------|-------|\n")

	layerPairs := make(map[string]int)
	for _, v := range violations {
		key := fmt.Sprintf("%s → %s", v.SourceLayer, v.TargetLayer)
		layerPairs[key]++
	}

	for pair, count := range layerPairs {
		sb.WriteString(fmt.Sprintf("| %s | %d |\n", pair, count))
	}
	sb.WriteString("\n")

	// Detailed Violations
	sb.WriteString("## Detailed Violations\n\n")

	for _, v := range violations {
		sb.WriteString(fmt.Sprintf("### %s\n\n", v.ID))
		sb.WriteString(fmt.Sprintf("**File:** `%s:%d`\n\n", v.File, v.Line))
		sb.WriteString(fmt.Sprintf("**Rule:** `%s`\n\n", v.RuleID))
		sb.WriteString(fmt.Sprintf("**Severity:** %s\n\n", strings.Title(strings.ToLower(string(v.Severity)))))
		sb.WriteString(fmt.Sprintf("**Import:** `%s`\n\n", v.Import))

		sb.WriteString("**Why This Matters:**\n\n")
		sb.WriteString(fmt.Sprintf("%s\n\n", v.Message))

		sb.WriteString("---\n\n")
	}

	// Recommendations
	sb.WriteString("## Recommendations\n\n")

	if totalErrors > 0 {
		sb.WriteString("### Critical Actions Required\n\n")
		sb.WriteString("1. **Address all errors first** - These are architectural violations that break Clean/Hexagonal Architecture principles\n")
		sb.WriteString("2. **Start with domain layer violations** - Domain purity is the foundation of good architecture\n")
		sb.WriteString("3. **Use Dependency Inversion** - Define interfaces in domain, implement in infrastructure\n\n")
	}

	if totalWarnings > 0 {
		sb.WriteString("### Warnings to Review\n\n")
		sb.WriteString("Warnings are architectural concerns that should be addressed but don't block deployment.\n\n")
		sb.WriteString("Schedule time to refactor these in upcoming sprints.\n\n")
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Report generated by Arx v%s - Architecture audit CLI*\n", r.version))
	sb.WriteString("\nRun `arx explain <violation-id>` for detailed guidance on specific violations.\n")

	return sb.String()
}

// GenerateCommitMessage generates a commit message for the report
func GenerateCommitMessage(violations []domain.Violation) string {
	if len(violations) == 0 {
		return "docs: architecture audit - no violations found"
	}

	errors := 0
	warnings := 0
	for _, v := range violations {
		if strings.ToLower(string(v.Severity)) == "error" {
			errors++
		} else {
			warnings++
		}
	}

	return fmt.Sprintf("docs: architecture audit - %d errors, %d warnings", errors, warnings)
}
